project:
  type: website
  output-dir: docs

website:
  title: "Mariah Webb"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resume.qmd
        text: Résumé

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source